on: push

jobs:
  code_style:
   runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Check out code
      - name: Python Style Checker
        uses: andymckay/pycodestyle-action@0.1.3

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Check out code
        
      - uses: docker/build-push-action@v1
        name: Building
        with:
          username: ${{ secrets.user2 }}
          password: ${{ secrets.password2 }}
          repository: artemaro2/workflow
          dockerfile: dockerfile
          tags: first
