on: push

jobs:
  code_style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Check out code
      - name: Python Style Checker
        uses: andymckay/pycodestyle-action@0.1.3
        
  
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build test docker image
        run: |
           docker build -t lab1_docker:latest .
           docker build -f tests/dockerfile -t lab1_test_docker:latest .
      - name: Run tests
        run: docker run lab1_test_docker:latest
  
  
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Check out code
        
      - uses: docker/build-push-action@v1
        name: Building
        with:
          username: ${{ secrets.user2 }}
          password: ${{ secrets.password2 }}
          repository: artemaro2/workflow
          dockerfile: dockerfile
          tags: first


