on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Python Style Checker
        uses: andymckay/pycodestyle-action@0.1.3

      - uses: docker/build-push-action@v1
        name: Building
        with:
          username: ${{ secrets.user2 }}
          password: ${{ secrets.password2 }}
          repository: artemaro2/workflow
          dockerfile: dockerfile
          tags: first
