on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Check out code

      - uses: docker/build-push-action@v1
        name: Build & push Docker image
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
          repository: orrrrtem/workflow_base
          dockerfile: dockerfile
          tags: first
